spring:
  application:
    name: safaricom-task
  datasource:
    username: reptilefury
    url: jdbc:mysql://localhost:3306/SAFARICOM_TASK
    password: password
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  file:
    name: ./logs/${spring.application.name}.log
