spring:
  application:
    name: safaricom-task
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/codility
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  file:
    name: ./logs/${spring.application.name}.log